apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: hello-app.corp.com.1.0.0
spec:
  refName: hello-app.corp.com
  version: 1.0.0
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: index.docker.io/100mik/hello-app@sha256:29c02895e51a0157ff844afd97a8ccd42a7ba0dd2e89bf5f9c6a668e17482ccb
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
  valuesSchema:
    openAPIv3:
      title: hello-app.corp.com.1.0.0 values schema
      examples:
        - user_name: stranger
        - svc_port: 8081
      properties:
        user_name:
          type: string
          description: The name the app uses to greet the user
          default: stranger
        svc_port:
          type: integer
          description: The port exposed by the service
          default: 8081