---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: simple-server-app
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    simple-app: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: simple-server-app
spec:
  replicas: 3
  selector:
    matchLabels:
      simple-app: ""
  template:
    metadata:
      labels:
        simple-app: ""
    spec:
      containers:
      - name: simple-server-app
        image: docker.io/prewar/simple-server:latest
        env:
        - name: USER_NAME
          value: "stranger"
