---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: simple-server-app
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    simple-app: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: simple-server-app
spec:
  replicas: 3
  selector:
    matchLabels:
      simple-app: ""
  template:
    metadata:
      labels:
        simple-app: ""
    spec:
      containers:
      - name: simple-server-app
        image: docker.io/prewar/simple-server:latest
        envFrom:
          - configMapRef:
              name: simple-app-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-app-config
  annotations:
    kapp.k14s.io/versioned: ""
data:
  USER_NAME: John Doe
