#@ load("@ytt:data", "data")

#@ def labels():
simple-app: ""
#@ end

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: simple-server-app
spec:
  ports:
  - port: #@ data.values.svc_port
    targetPort: #@ data.values.app_port
  selector: #@ labels()
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: simple-server-app
spec:
  replicas: 3
  selector:
    matchLabels: #@ labels()
  template:
    metadata:
      labels: #@ labels()
    spec:
      containers:
      - name: simple-server-app
        image: docker.io/prewar/simple-server:latest
        envFrom:
          - configMapRef:
              name: simple-app-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-app-config
  annotations:
    kapp.k14s.io/versioned: ""
data:
  USER_NAME: #@ data.values.user_name
